/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Rmp;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.MessageFormat;
import java.text.*;
import java.awt.*;
/**
 *
 * @author reception1
 */
public class Rmp extends javax.swing.JFrame {
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DefaultTableModel model = new DefaultTableModel();
    

    /**
     * Creates new form Rmp
     */
    public Rmp() {
        initComponents();
        
        Object col[] ={"Room","SetAs","Date","Type","B/S","View","Balcony","Name"};
        
        model.setColumnIdentifiers(col);
        jTable1.setModel(model);
        conn = Rmp.ConnectDB();
        
        
        UpdateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboSetAs = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboBs = new javax.swing.JComboBox<>();
        cboRoom = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cboView = new javax.swing.JComboBox<>();
        cboBalcony = new javax.swing.JComboBox<>();
        cboType = new javax.swing.JComboBox<>();
        jtxName = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonAddRoom = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Type:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 80, 30));

        cboSetAs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboSetAs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "1 DBL", "1 DBL + 1 SGL", "1 DBL + 2 SGL", "2 SGL", "3 SGL", "4 SGL" }));
        cboSetAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSetAsActionPerformed(evt);
            }
        });
        jPanel1.add(cboSetAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 170, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Date:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("B/S:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("View:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 80, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Balcony:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 80, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Set As:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Room:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 30));

        cboBs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboBs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "SHOWER", "BATHTUB" }));
        jPanel1.add(cboBs, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 130, 30));

        cboRoom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "001", "002", "003", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "201", "202", "203", "204", "205", "206", "207", "208", "209", "210", "211", "212", "213", "214", "215", "301", "302", "303", "304", "305", "306", "307", "308", "309", "310", "311", "401", "402", "403" }));
        jPanel1.add(cboRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 110, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 80, 30));

        cboView.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboView.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "NO", "BACK", "INTERNAL", "STREET" }));
        cboView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboViewActionPerformed(evt);
            }
        });
        jPanel1.add(cboView, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 130, 30));

        cboBalcony.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboBalcony.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "BALCONY", "BIG BALCONY", "WINDOW ONLY" }));
        jPanel1.add(cboBalcony, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 120, 30));

        cboType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "TRAD", "ST", "EXE", "BAS", "QUAD", "3PL" }));
        jPanel1.add(cboType, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 130, 30));

        jtxName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtxName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 120, 30));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 92, 170, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 140));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdate.setText("UPDATE");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 130, 40));

        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDelete.setText("DELETE");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 130, 40));

        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonReset.setText("RESET");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 130, 40));

        jButtonPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPrint.setText("PRINT");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 130, 40));

        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonExit.setText("EXIT");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 80, 40));

        jButtonAddRoom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddRoom.setText("ADD ROOM");
        jButtonAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddRoomActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAddRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 730, 50));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room", "Set As", "Date", "Type", "B/S", "View", "Balcony", "Title"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 180));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 730, 180));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public static Connection ConnectDB(){
    try
    {
        Class.forName("org.sqlite.JDBC");
        Connection conn = DriverManager.getConnection("jdbc:sqlite:dataform.db");
        return conn;
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null, e);
        return null;
    }
}

public void UpdateTable()
{
    conn = Rmp.ConnectDB();
    
    if (conn !=null)
    {
        String sql ="Select Room, SetAs, Date, Type, 'B/S', View, Balcony, Name from dataform";
        try
    {
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        Object[] columnData = new Object[8];
        
        while (rs.next()){
            columnData[0] = rs.getString("Room");
            columnData[1] = rs.getString("SetAs");
            columnData[2] = rs.getString("Date");
            columnData[3] = rs.getString("Type");
            columnData[4] = rs.getString("B/S");
            columnData[5] = rs.getString("View");
            columnData[6] = rs.getString("Balcony");
            columnData[7] = rs.getString("Name");
            model.addRow(columnData);
        }
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null, e);
        
    }
        
        
    }
}
    
    
    private void jButtonAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddRoomActionPerformed
     SimpleDateFormat Dformat = new SimpleDateFormat("dd-MM-yyyy"); 
      String sql ="INSERT INTO dataform( Room, SetAs, Date, Type, 'B/S', View, Balcony, Name)VALUES(?,?,?,?,?,?,?,?)";
        try
    {
        pst = conn.prepareStatement(sql);
        
           pst.setString(1, (String) cboRoom.getSelectedItem());
           pst.setString(2, (String) cboSetAs.getSelectedItem());
           pst.setString(3, Dformat.format(jDateChooser1.getDate()));
           pst.setString(4, (String) cboType.getSelectedItem());
           pst.setString(5, (String) cboBs.getSelectedItem());
           pst.setString(6, (String) cboView.getSelectedItem());
           pst.setString(7, (String) cboBalcony.getSelectedItem());
           pst.setString(8, jtxName.getText());
           
          pst.execute();
          JOptionPane.showMessageDialog(null,"System Updated");
          rs.close();
          pst.close();
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null, e);
        
    }  
        
    }//GEN-LAST:event_jButtonAddRoomActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
           
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       if(jTable1.getSelectedRow()==-1){
            if(jTable1.getRowCount()==0){
                
                JOptionPane.showMessageDialog(null, "No data to Delete!!!",
                        "Form",JOptionPane.OK_OPTION);
                
            }else{

                JOptionPane.showMessageDialog(null, "Select a Row to Delete!!!",
                         "Form",JOptionPane.OK_OPTION);

            }
        }else{
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
    
    MessageFormat  header = new MessageFormat("Printing in progress");
    
            MessageFormat footer  = new MessageFormat("Page (0,number,integer)");
            try
            {
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);;
            
            }
            catch (java.awt.print.PrinterException e){
                    System.err.format("No Printer Found", e.getMessage());
            }      
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void cboSetAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSetAsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSetAsActionPerformed

private JFrame frame;
    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
     
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Do you really want to exit?","Roomz Management Program ",
                JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        try
        {
            cboRoom.setSelectedIndex(0);
            cboSetAs.setSelectedIndex(0);
            jDateChooser1.setDate(null);
            cboType.setSelectedIndex(0);
            cboBs.setSelectedIndex(0);
            cboView.setSelectedIndex(0);
            cboBalcony.setSelectedIndex(0);
            jtxName.setText(null);
        }
        catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void cboViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboViewActionPerformed

    }//GEN-LAST:event_cboViewActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
           SimpleDateFormat Dformat = new SimpleDateFormat("dd-MM-yyyy"); 
      String sql ="INSERT INTO dataform( Room, SetAs, Date, Type, 'B/S', View, Balcony, Name)VALUES(?,?,?,?,?,?,?,?)";
        try
    {
        pst = conn.prepareStatement(sql);
        
           pst.setString(1, (String) cboRoom.getSelectedItem());
           pst.setString(2, (String) cboSetAs.getSelectedItem());
           pst.setString(3, Dformat.format(jDateChooser1.getDate()));
           pst.setString(4, (String) cboType.getSelectedItem());
           pst.setString(5, (String) cboBs.getSelectedItem());
           pst.setString(6, (String) cboView.getSelectedItem());
           pst.setString(7, (String) cboBalcony.getSelectedItem());
           pst.setString(8, jtxName.getText());
           
          pst.execute();
          JOptionPane.showMessageDialog(null,"System Updated");
          rs.close();
          pst.close();
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null, e);
        
    }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboBalcony;
    private javax.swing.JComboBox<String> cboBs;
    private javax.swing.JComboBox<String> cboRoom;
    private javax.swing.JComboBox<String> cboSetAs;
    private javax.swing.JComboBox<String> cboType;
    private javax.swing.JComboBox<String> cboView;
    private javax.swing.JButton jButtonAddRoom;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonUpdate;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxName;
    // End of variables declaration//GEN-END:variables
}
